version: 2.1

jobs:
  build:
    executor: win/default

    steps:
      - checkout
      - run:
          name: Build project
          command: dotnet build
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
